// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwxvyphakrtrprelckqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3eHZ5cGhha3J0cnByZWxja3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDQ2MjIsImV4cCI6MjA2ODE4MDYyMn0.gPy3CQQ-xE1fh6GGR1_B9ZOe9Qo3sj7lOieRio_yADU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});